apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: lifeplan-monitor
  name: lifeplan-monitor
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: lifeplan-monitor
status:
  loadBalancer: {}
