apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: lifeplan-monitor
  name: lifeplan-monitor
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: lifeplan-monitor
status:
  loadBalancer: {}
