apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: lifeplan-monitor
  name: lifeplan-monitor
spec:
  replicas: 1
  selector:
    io.kompose.service: lifeplan-monitor
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: lifeplan-monitor
    spec:
      containers:
        - env:
            - name: LIFEPLAN_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: LIFEPLAN_API_TOKEN
                    name: env
            - name: LIFEPLAN_API_URL
              value: https://lifeplan-staging.luomus.fi/api/v1/activities
            - name: MONITOR_COMPLETED_MAX_AGE
              value: 7
            - name: MONITOR_DB_HOST
                valueFrom:
                  secretKeyRef:
                    key: MONITOR_DB_HOST
                    name: env
            - name: MONITOR_DB_NAME
                valueFrom:
                  secretKeyRef:
                    key: MONITOR_DB_NAME
                    name: env
            - name: MONITOR_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: MONITOR_DB_PASSWORD
                    name: env
            - name: MONITOR_DB_USER
                valueFrom:
                  secretKeyRef:
                    key: MONITOR_DB_USER
                    name: env
            - name: MONITOR_FAILED_MAX_AGE
              value: 14
            - name: MONITOR_INPROGRESS_MAX_AGE
              value: 14
            - name: MONITOR_PARTIAL_MAX_AGE
              value: 14
            - name: MONITOR_SECRET
                valueFrom:
                  secretKeyRef:
                    key: MONITOR_SECRET
                    name: env
            - name: MONITOR_SECURE
              value: 'true'
            - name: MONITOR_SESSION_DB_NAME
                valueFrom:
                  secretKeyRef:
                    key: MONITOR_SESSION_DB_NAME
                    name: env
          image: luomus/lifeplan-monitor
          name: lifeplan-monitor
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - lifeplan-monitor
        from:
          kind: ImageStreamTag
          name: luomus/lifeplan-monitor:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
