apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: lifeplan-monitor
  name: lifeplan-monitor
spec:
  replicas: 1
  selector:
    io.kompose.service: lifeplan-monitor
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: lifeplan-monitor
    spec:
      containers:
        - env:
          - name: LIFEPLAN_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: LIFEPLAN_API_TOKEN
                name: monitor
          - name: LIFEPLAN_API_URL
            valueFrom:
              secretKeyRef:
                key: LIFEPLAN_API_URL
                name: monitor
          - name: MONITOR_COMPLETED_MAX_AGE
            valueFrom:
              secretKeyRef:
                key: MONITOR_COMPLETED_MAX_AGE
                name: monitor
          - name: MONITOR_DB_HOST
            valueFrom:
              secretKeyRef:
                key: MONITOR_DB_HOST
                name: monitor
          - name: MONITOR_DB_NAME
            valueFrom:
              secretKeyRef:
                key: MONITOR_DB_NAME
                name: monitor
          - name: MONITOR_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MONITOR_DB_PASSWORD
                name: monitor
          - name: MONITOR_DB_USER
            valueFrom:
              secretKeyRef:
                key: MONITOR_DB_USER
                name: monitor
          - name: MONITOR_FAILED_MAX_AGE
            valueFrom:
              secretKeyRef:
                key: MONITOR_FAILED_MAX_AGE
                name: monitor
          - name: MONITOR_INPROGRESS_MAX_AGE
            valueFrom:
              secretKeyRef:
                key: MONITOR_INPROGRESS_MAX_AGE
                name: monitor
          - name: MONITOR_PARTIAL_MAX_AGE
            valueFrom:
              secretKeyRef:
                key: MONITOR_PARTIAL_MAX_AGE
                name: monitor
          - name: MONITOR_SECRET
            valueFrom:
              secretKeyRef:
                key: MONITOR_SECRET
                name: monitor
          - name: MONITOR_SECURE
            valueFrom:
              secretKeyRef:
                key: MONITOR_SECURE
                name: monitor
          - name: MONITOR_SESSION_DB_NAME
            valueFrom:
              secretKeyRef:
                key: MONITOR_SESSION_DB_NAME
                name: monitor
          image: luomus/lifeplan-monitor
          name: lifeplan-monitor
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - lifeplan-monitor
        from:
          kind: ImageStreamTag
          name: lifeplan-monitor
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
